sudo: required
language: generic
services:
  - docker

before_install:
  - docker build -t stubbornfox/react-test -f './client/Dockerfile.dev' ./client

script:
  - docker run -e CI=true stubbornfox/react-test npm test

after_success:
  - docker build -t stubbornfox/multi-client ./client
  - docker build -t stubbornfox/multi-nginx ./nginx
  - docker build -t stubbornfox/multi-server ./server
  - docker build -t stubbornfox/multi-worker ./worker
