sudo: required
language: generic
services:
  - docker

before_install:
  - docker build -t stubbornfox/react-test -f './client/Dockerfile.dev' ./client

script:
  - docker run -e CI=true stubbornfox/react-test npm test

after_success:
  - docker build -t stubbornfox/multi-client ./client
  - docker build -t stubbornfox/multi-nginx ./nginx
  - docker build -t stubbornfox/multi-server ./server
  - docker build -t stubbornfox/multi-worker ./worker
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  - docker push stubbornfox/multi-client
  - docker push stubbornfox/multi-nginx
  - docker push stubbornfox/multi-server
  - docker push stubbornfox/multi-worker

deploy:
  provider: elasticbeanstalk
  region: 'us-east-1'
  app: 'multi-docker'
  env: 'Multi-docker-env'
  bucket_name: 'elasticbeanstalk-us-east-1-088374349697'
  bucket_path: 'multi-docker'
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
